# 修改启动端口号
server:
  port: 8091

# 配置spring
spring:
  # redis
  redis:
    host: 47.97.228.152
    port: 6379
    password: redis#@!123
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shop
    password: shop#@!123
    url: jdbc:mysql://47.97.228.152:3306/shop?useSSL=false&useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2B8
  jpa:
    open-in-view: true


# 手机/邮箱验证
sms:
  smsAccountSid: 8a216da87955ba190179592c72e100f6
  smsAuthToken: 5abcc0c81dea4ddcba65faa19ecec3b8
  smsAppID: 8a216da87955ba190179592c73ac00fd
  smsServerIP: app.cloopen.com
  smsServerPort: 8883
